### ISSUE TITLE
AirBrake doesn't report error with bundle exec rake airbrake:test --trace

### ISSUE THREAD

**Issue by dashbitla** [airbrake/airbrake#237]
Here is the response when I run the Airbrake test. 
It exits with no response after the below line

```
  Started GET "/verify" for  at 2013-08-21 03:17:04 -0700
```

The same setup is working for a different App with same rails version and same Airbrake version. 

Is Airbrake conflicts with any other Gems?? 

```
    ** Execute airbrake:test
    Configuration:
                      api_key: "[my-key]"
                   js_api_key: "a19e7fe6dded5bea1d7429d355d0a992"
            backtrace_filters: [#<Proc:0x007f99b39ebf70@/Users/dashbitla/.rvm/gems/rub
     development_environments: []
           development_lookup: true
             environment_name: "demo"
                         host: "api.airbrake.io"
            http_open_timeout: 2
            http_read_timeout: 5
                       ignore: ["ActiveRecord::RecordNotFound", "ActionController::Rou
            ignore_by_filters: []
            ignore_user_agent: []
                notifier_name: "Airbrake Notifier"
                 notifier_url: "https://github.com/airbrake/airbrake"
             notifier_version: "3.1.13"
               params_filters: ["password", "password_confirmation"]
                 project_root: #<Pathname:/Users/dashbitla/w/bitlasoft/ticket-simply-t
                         port: 80
                     protocol: "http"
                   proxy_host: nil
                   proxy_pass: nil
                   proxy_port: nil
                   proxy_user: nil
                       secure: false
    use_system_ssl_cert_chain: false
                    framework: "Rails: 3.2.13"
             user_information: "Airbrake Error {{error_id}}"
       rescue_rake_exceptions: nil
     rake_environment_filters: []
                    test_mode: nil
    Setting up the Controller.
    Processing request.


    Started GET "/verify" for  at 2013-08-21 03:17:04 -0700
```
