### ISSUE TITLE
Airbrake not compatible with better_errors

### ISSUE THREAD

**Issue by teknull** [airbrake/airbrake#347]
I have a Rails 3.2.20 app in which I use `better_errors` and `binding_of_caller` in my development gemset.

My goal is to try and have AirBrake fire notifications when in the development environment.  After going back and forth with support and experimenting on my own it seems that `better_errors` does not allow `airbrake` to fire an exception and notify.

Here is what my Gemfile looks like

```
source 'https://rubygems.org'

# Bundle edge Rails instead:
gem 'rails',  '~> 3.2.19'
gem 'pg', "~> 0.14.0"
gem 'devise', "~> 2.1.2"
gem "combined_time_select", "~> 0.0.1"
gem "will_paginate", "~> 3.0.3"
gem 'whenever', "~> 0.7.3", :require => false
gem "gritter", "1.0.2"
gem "rails_admin", "~> 0.3.0"
gem "twitter-bootstrap-rails", "~> 2.2.1"
gem "will_paginate-bootstrap", "~> 0.2.2"
gem "prawn"
gem 'twilio-ruby', '~> 3.11.6'
gem 'carrierwave', '~> 0.10.0'
gem 'geocoder', '~> 1.2.5'
gem 'attribute_normalizer', '~> 1.2.0'
gem 'chartkick', '~> 1.3.2'
gem 'groupdate'
gem 'airbrake'




group :development do
  gem "annotate", "~> 2.5.0"
  gem "better_errors", "~> 0.3.2"
  gem "binding_of_caller"
  gem 'thin', "~> 1.4.1"
  gem 'brakeman', :require => false
end

gem "gmaps4rails", "~> 2.0.0.pre"
gem "taip_parser", "~> 0.0.1"
gem "foreman", "~> 0.60.0"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', '~> 0.12.1', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-datatables-rails'
end

gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem 'jquery-rails'

# Deploy with Capistrano
gem 'capistrano'
```

Here's my `airbrake.rb` initializer:
```
Airbrake.configure do |config|
  config.api_key = 'blahblahblah'
  config.development_environments = []
  config.ignore_only = []
  config.secure = true
  config.http_open_timeout = 1 # defaults to 2 (seconds)
  config.http_read_timeout = 3 # defaults to 5 (seconds)
  config.user_information = "<p>AirBrake Error ID: <strong>{{ error_id }}</strong>.</p>"
  config.development_lookup = false
end
```
Here's the output of `bundle exec rake airbrake:test --trace`
```
bundle exec rake airbrake:test --trace
** Invoke airbrake:test (first_time)
** Invoke environment (first_time)
** Invoke rails_admin:disable_initializer (first_time)
** Execute rails_admin:disable_initializer
[RailsAdmin] RailsAdmin initialization disabled by default. Pass SKIP_RAILS_ADMIN_INITIALIZER=false if you need it.
** Execute environment
** Execute airbrake:test
Configuration:
                  api_key: "blahblahblah"
        backtrace_filters: [#<Proc:0x007fd9e544a2c0@/Users/jamesjelinek/.rbenv/ver
 development_environments: []
       development_lookup: false
         environment_name: "development"
                     host: "api.airbrake.io"
        http_open_timeout: 1
        http_read_timeout: 3
                   ignore: []
        ignore_by_filters: []
        ignore_user_agent: []
            notifier_name: "Airbrake Notifier"
             notifier_url: "https://github.com/airbrake/airbrake"
         notifier_version: "4.1.0"
           params_filters: ["password", "password_confirmation"]
             project_root: #<Pathname:/Users/jamesjelinek/Dropbox/exigencad>
                     port: 443
                 protocol: "https"
               proxy_host: nil
               proxy_pass: nil
               proxy_port: nil
               proxy_user: nil
                   secure: true
use_system_ssl_cert_chain: false
                framework: "Rails: 3.2.20"
         user_information: "<p>AirBrake Error ID: <strong>{{ error_id }}</strong>.
   rescue_rake_exceptions: nil
 rake_environment_filters: []
                test_mode: nil
Setting up the Controller.
Processing request.


Started GET "/verify" for  at 2014-11-13 10:12:38 -0600
Raising 'AirbrakeTestingException' to simulate application failure.
```

If you notice airbrake does not get notified of the simulated exception.  Here's what happens when I remove `better_errors` and `binding_of_caller`

```
bundle exec rake airbrake:test --trace
** Invoke airbrake:test (first_time)
** Invoke environment (first_time)
** Invoke rails_admin:disable_initializer (first_time)
** Execute rails_admin:disable_initializer
[RailsAdmin] RailsAdmin initialization disabled by default. Pass SKIP_RAILS_ADMIN_INITIALIZER=false if you need it.
** Execute environment
** Execute airbrake:test
Configuration:
                  api_key: "blahblahblah"
        backtrace_filters: [#<Proc:0x007fc7d4ce8918@/Users/jamesjelinek/.rbenv/ver
 development_environments: []
       development_lookup: false
         environment_name: "development"
                     host: "api.airbrake.io"
        http_open_timeout: 1
        http_read_timeout: 3
                   ignore: []
        ignore_by_filters: []
        ignore_user_agent: []
            notifier_name: "Airbrake Notifier"
             notifier_url: "https://github.com/airbrake/airbrake"
         notifier_version: "4.1.0"
           params_filters: ["password", "password_confirmation"]
             project_root: #<Pathname:/Users/jamesjelinek/Dropbox/exigencad>
                     port: 443
                 protocol: "https"
               proxy_host: nil
               proxy_pass: nil
               proxy_port: nil
               proxy_user: nil
                   secure: true
use_system_ssl_cert_chain: false
                framework: "Rails: 3.2.20"
         user_information: "<p>AirBrake Error ID: <strong>{{ error_id }}</strong>.
   rescue_rake_exceptions: nil
 rake_environment_filters: []
                test_mode: nil
Setting up the Controller.
Processing request.


Started GET "/verify" for  at 2014-11-13 10:09:48 -0600
Raising 'AirbrakeTestingException' to simulate application failure.
** [Airbrake] Success: Net::HTTPOK
** [Airbrake] Environment Info: [Ruby: 1.9.3] [Rails: 3.2.20] [Env: development]
** [Airbrake] Response from Airbrake: 
UUID: 1288414598388681756
URL:  https://airbrake.io/locate/1288414598388681756

Testing airbrake via "rake airbrake:test". If you can see this, it works.
```

As you can see by removing `better_errors` and `binding_of_caller` airbrake will fire and notify the API of an exception.

I'm sure I'm not the only Rails dev out there using `better_errors` so there must be a way to get these to work in unison to fire development environment exceptions.

I'm not sure if this is considered a bug or just a lack of compatibility but I figured I would open an issue for review.
