### ISSUE TITLE
rake airbrake:test fails with ActionController::RoutingError

### ISSUE THREAD

**Issue by vesan** [airbrake/airbrake#9]
When I run `bundle exec rake airbrake:test --trace` I get this:

```
** Invoke airbrake:test (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute airbrake:test
Configuration:
                  api_key: "[my-api-key]"
        backtrace_filters: [#<Proc:0x000001051f3708@/Users/vesan/.rvm/gems/ruby-1.
 development_environments: []
       development_lookup: true
         environment_name: "development"
                     host: "airbrakeapp.com"
        http_open_timeout: 2
        http_read_timeout: 5
                   ignore: ["ActiveRecord::RecordNotFound", "ActionController::Rou
        ignore_by_filters: []
        ignore_user_agent: []
            notifier_name: "Airbrake Notifier"
             notifier_url: "http://airbrakeapp.com"
         notifier_version: "3.0.2"
           params_filters: ["password", "password_confirmation"]
             project_root: #<Pathname:/Volumes/Kisko/project/code>
                     port: 80
                 protocol: "http"
               proxy_host: nil
               proxy_pass: nil
               proxy_port: nil
               proxy_user: nil
                   secure: false
                framework: "Rails: 3.0.9"
         user_information: "Airbrake Error {{error_id}}"
   rescue_rake_exceptions: nil
Setting up the Controller.
Processing request.


Started GET "/verify" for  at 2011-09-02 16:53:19 +0300

ActionController::RoutingError (No route matches "/verify"):
```

Before that I have added `gem "airbrake", "3.0.2"` to Gemfile & run `bundle` & run `script/rails generate airbrake --api-key [my-api-key]`.

What could cause this kind of behaviour?
